server:  port: 8081
spring:
  application:
    name: user-service
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: Sw@th!07071995
  jpa:    hibernate:      ddl-auto: update    show-sql: true    properties:      hibernate:        dialect: org.hibernate.dialect.MySQL8Dialect  